[formatting]
  align_entries       = true
  allowed_blank_lines = 2
  array_auto_expand   = false
  column_width        = 120
  indent_entries      = true
  indent_string       = "  "
  indent_tables       = true
  reorder_arrays      = true
  reorder_keys        = true
  trailing_newline    = true
